version: '3'
services:
  nginx:
    container_name: watchnext_nginx
    build: config/docker/nginx
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/html/'
      - './config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
  php:
    container_name: watchnext_php
    build: config/docker/php
    volumes:
      - './:/var/www/html/'
      - './config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './config/docker/php/apcu.ini:/usr/local/etc/php/conf.d/docker-php-ext-apcu.ini'
  mysql:
    container_name: watchnext_mysql
    image: mariadb
    ports:
      - '3301:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: watchnext
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
  mail:
    container_name: watchnext_mail
    image: mailhog/mailhog
    ports:
      - '8025:8025'
  memcached:
    container_name: watchnext_memcached
    image: memcached
    ports:
      - '11211:11211'
  node:
    container_name: watchnext_node
    build: config/docker/node
    volumes:
      - './:/var/app'
